README.adoc
docs/AboutUs.adoc
docs/DevOps.adoc
docs/DeveloperGuide.adoc
docs/Documentation.adoc
docs/SettingUp.adoc
docs/Testing.adoc
docs/UserGuide.adoc

Modify documentations to reflect our team identity.

Modify team information

---

docs/UserGuide.adoc

Fix incorrect budget examples

---

docs/UserGuide.adoc

Update user guide for analytics

---

docs/UserGuide.adoc

Update user guide for wealth and transactions

---

docs/UserGuide.adoc

Update user guide for repeating transactions

---

docs/DeveloperGuide.adoc

Please actually review this and provide suggestions for how to phrase target user profile and value proposition

Update target user profile and value proposition in dev guide

---

README.adoc
build.gradle

Update README and build.gradle for v1.1 shortfall

---

src/main/java/seedu/address/model/Amount.java

Goals of this PR:
Implement methods and numerical value for Amount.

Modify Amount class

---

src/main/java/seedu/ichifund/model/Amount.java
src/main/java/seedu/ichifund/model/FundBook.java
src/main/java/seedu/ichifund/model/ReadOnlyFundBook.java
src/main/java/seedu/ichifund/model/budget/Budget.java
src/main/java/seedu/ichifund/model/budget/UniqueBudgetList.java
src/main/java/seedu/ichifund/model/budget/exceptions/BudgetNotFoundException.java
src/main/java/seedu/ichifund/model/budget/exceptions/DuplicateBudgetException.java
src/test/java/seedu/ichifund/model/FundBookTest.java
src/test/java/seedu/ichifund/testutil/BudgetBuilder.java

Implement basic Budget models

---

src/main/java/seedu/ichifund/logic/parser/AddTransactionCommandParser.java
src/main/java/seedu/ichifund/model/date/Date.java
src/main/java/seedu/ichifund/model/date/Day.java
src/main/java/seedu/ichifund/model/date/Month.java
src/main/java/seedu/ichifund/model/date/Year.java

Add checking for valid Date

---

docs/UserGuide.adoc
src/main/java/seedu/ichifund/commons/core/Messages.java
src/main/java/seedu/ichifund/logic/commands/budget/DeleteBudgetCommand.java
src/main/java/seedu/ichifund/logic/parser/IchiFundParser.java
src/main/java/seedu/ichifund/logic/parser/budget/DeleteBudgetCommandParser.java

Implement budget deletion

---

src/main/java/seedu/ichifund/logic/parser/budget/AddBudgetCommandParser.java
src/main/java/seedu/ichifund/model/budget/Budget.java
src/main/java/seedu/ichifund/model/date/Year.java
src/main/java/seedu/ichifund/storage/JsonAdaptedBudget.java
src/main/java/seedu/ichifund/ui/BudgetCard.java
src/main/resources/view/BudgetListCard.fxml
src/test/java/seedu/ichifund/testutil/BudgetBuilder.java

This PR is purely for model and UI.

Add criteria in Budget

---

src/main/java/seedu/ichifund/logic/commands/transaction/AddTransactionCommand.java
src/main/java/seedu/ichifund/logic/parser/AddTransactionCommandParser.java
src/main/java/seedu/ichifund/logic/parser/IchiFundParser.java
src/main/java/seedu/ichifund/logic/parser/transaction/AddTransactionCommandParser.java
src/main/java/seedu/ichifund/model/FundBook.java
src/main/java/seedu/ichifund/model/Model.java
src/main/java/seedu/ichifund/model/ModelManager.java
src/main/java/seedu/ichifund/model/ReadOnlyFundBook.java
src/main/java/seedu/ichifund/model/date/Date.java
src/main/java/seedu/ichifund/model/transaction/Transaction.java
src/main/java/seedu/ichifund/model/transaction/TransactionList.java
src/main/java/seedu/ichifund/model/transaction/TransactionType.java
src/main/java/seedu/ichifund/model/transaction/exceptions/TransactionNotFoundException.java
src/main/java/seedu/ichifund/storage/JsonAdaptedDate.java
src/main/java/seedu/ichifund/storage/JsonAdaptedTransaction.java
src/main/java/seedu/ichifund/storage/JsonSerializableFundBook.java
src/test/data/JsonSerializableFundBookTest/duplicatePersonFundBook.json
src/test/data/JsonSerializableFundBookTest/invalidPersonFundBook.json
src/test/data/JsonSerializableFundBookTest/typicalPersonsFundBook.json
src/test/java/seedu/ichifund/logic/commands/AddCommandTest.java
src/test/java/seedu/ichifund/model/FundBookTest.java
src/test/java/seedu/ichifund/testutil/DateBuilder.java
src/test/java/seedu/ichifund/testutil/TransactionBuilder.java

Basically everything basic except for UI is done in this PR.
Things to note:
1) @LeeYiyuan I have a `TransactionType` field to distinguish between income and expenditure. It works like the other `String` data field classes except it only allows two values.
1) I have decided to allow duplicates in `TransactionList` for user considerations.

Implement transaction add model, logic, storage

---

src/main/java/seedu/ichifund/commons/core/Messages.java
src/main/java/seedu/ichifund/logic/commands/transaction/AddTransactionCommand.java
src/main/java/seedu/ichifund/logic/commands/transaction/FilterTransactionCommand.java
src/main/java/seedu/ichifund/logic/parser/IchiFundParser.java
src/main/java/seedu/ichifund/logic/parser/ParserUtil.java
src/main/java/seedu/ichifund/logic/parser/transaction/AddTransactionCommandParser.java
src/main/java/seedu/ichifund/logic/parser/transaction/FilterTransactionCommandParser.java
src/main/java/seedu/ichifund/model/date/Date.java
src/main/java/seedu/ichifund/model/transaction/Category.java
src/main/java/seedu/ichifund/model/transaction/Transaction.java
src/main/java/seedu/ichifund/model/transaction/TransactionCategoryPredicate.java
src/main/java/seedu/ichifund/model/transaction/TransactionDatePredicate.java

For the curious:
I am eventually enforcing a month/year filter even when the app starts up, so month and year are compulsory fields. I probably need to refactor optional fields here and there.
Fixes #58

Implement transaction filter

---

src/main/java/seedu/ichifund/logic/commands/transaction/FilterTransactionCommand.java
src/main/java/seedu/ichifund/logic/parser/transaction/FilterTransactionCommandParser.java
src/main/java/seedu/ichifund/model/Description.java
src/main/java/seedu/ichifund/model/FundBook.java
src/main/java/seedu/ichifund/model/Model.java
src/main/java/seedu/ichifund/model/ModelManager.java
src/main/java/seedu/ichifund/model/context/Context.java
src/main/java/seedu/ichifund/model/context/TransactionContext.java
src/main/java/seedu/ichifund/model/date/Date.java
src/main/java/seedu/ichifund/model/date/Day.java
src/main/java/seedu/ichifund/model/date/Month.java
src/main/java/seedu/ichifund/model/date/Year.java
src/main/java/seedu/ichifund/model/transaction/Transaction.java
src/main/java/seedu/ichifund/model/transaction/TransactionList.java
src/test/java/seedu/ichifund/logic/commands/AddCommandTest.java

Transaction context

---

src/main/resources/view/BudgetListCard.fxml
src/main/resources/view/CommandBox.fxml
src/main/resources/view/IchiTheme.css
src/main/resources/view/MainWindow.fxml
src/main/resources/view/ResultDisplay.fxml
src/main/resources/view/TransactionListCard.fxml

I still found the previous UI to be pretty kiddish. So this PR is to modernize the UI.

Beautify UI elements

---

src/main/java/seedu/ichifund/logic/Logic.java
src/main/java/seedu/ichifund/logic/LogicManager.java
src/main/java/seedu/ichifund/model/Model.java
src/main/java/seedu/ichifund/model/ModelManager.java
src/main/java/seedu/ichifund/model/context/TransactionContext.java
src/main/java/seedu/ichifund/model/date/Date.java
src/main/java/seedu/ichifund/model/date/Month.java
src/main/java/seedu/ichifund/model/transaction/TransactionType.java
src/main/java/seedu/ichifund/ui/MainWindow.java
src/main/java/seedu/ichifund/ui/TransactionCard.java
src/main/java/seedu/ichifund/ui/TransactionListPanel.java
src/main/resources/view/IchiTheme.css
src/main/resources/view/TransactionListCard.fxml
src/main/resources/view/TransactionListPanel.fxml
src/test/java/seedu/ichifund/logic/commands/AddCommandTest.java

Fixes #126 
One concern: should the title of a list (Jan 2019 in the picture) have a bottom border? And if so, should I limit it to just under the Label for the title (not shown), or the entire HBox (in the picture)?

Add GUI to display transition context

---

src/main/java/seedu/ichifund/logic/Logic.java
src/main/java/seedu/ichifund/logic/LogicManager.java
src/main/java/seedu/ichifund/model/Model.java
src/main/java/seedu/ichifund/model/ModelManager.java
src/main/java/seedu/ichifund/ui/TransactionListPanel.java

Please just accept. I changed something without thinking it would break my GU before making my PR in #132  and changed it back.
Thanks!!

Fix bug in context GUI

---

docs/UserGuide.adoc

Creating new issue to populate UG with images.

Update user guide's out-of-date commands and overlooked AB3 references

---

src/main/java/seedu/ichifund/logic/commands/transaction/AddTransactionCommand.java
src/main/java/seedu/ichifund/model/Model.java
src/main/java/seedu/ichifund/model/ModelManager.java
src/main/java/seedu/ichifund/model/date/Date.java
src/main/java/seedu/ichifund/model/transaction/TransactionList.java
src/test/java/seedu/ichifund/logic/commands/AddCommandTest.java

@LeeYiyuan this should fix the issue faced in #160

Separate context update from adding transaction

---

src/main/java/seedu/ichifund/commons/core/Messages.java
src/main/java/seedu/ichifund/logic/commands/transaction/AddTransactionCommand.java
src/main/java/seedu/ichifund/logic/commands/transaction/DeleteTransactionCommand.java
src/main/java/seedu/ichifund/logic/commands/transaction/EditTransactionCommand.java
src/main/java/seedu/ichifund/logic/commands/transaction/FilterTransactionCommand.java
src/main/java/seedu/ichifund/logic/parser/transaction/DeleteTransactionCommandParser.java
src/main/java/seedu/ichifund/logic/parser/transaction/EditTransactionCommandParser.java
src/main/java/seedu/ichifund/logic/parser/transaction/TransactionFeatureParser.java
src/main/java/seedu/ichifund/model/transaction/Transaction.java

Implement edit and delete for transactions

---

docs/UserGuide.adoc
src/main/java/seedu/ichifund/commons/core/GuiSettings.java
src/main/java/seedu/ichifund/logic/parser/ParserUtil.java
src/main/java/seedu/ichifund/logic/parser/repeater/EditRepeaterCommandParser.java
src/main/java/seedu/ichifund/logic/parser/transaction/EditTransactionCommandParser.java
src/main/java/seedu/ichifund/model/amount/Amount.java
src/main/java/seedu/ichifund/model/date/Day.java
src/main/java/seedu/ichifund/model/date/Month.java
src/main/java/seedu/ichifund/model/date/Year.java
src/main/java/seedu/ichifund/model/transaction/Transaction.java
src/main/java/seedu/ichifund/storage/JsonAdaptedBudget.java
src/main/java/seedu/ichifund/storage/JsonAdaptedRepeater.java
src/main/java/seedu/ichifund/storage/JsonAdaptedTransaction.java
src/test/java/seedu/ichifund/logic/parser/ParserUtilTest.java
src/test/java/seedu/ichifund/model/amount/AmountTest.java

Documentation issues
- fixes #193  
- fixes #216 
- fixes #218 
- fixes #219 
GUI issues
- fixes #168 but need to review if 720px height is small enough
Other issues
- fixes #230 
- fixes parts of #236 (the newly checked parts in the checklist)

Fix some bugs

---

src/main/java/seedu/ichifund/MainApp.java
src/main/java/seedu/ichifund/model/util/SampleDataUtil.java

Hi, I've added sample data.
@LeeYiyuan you may want to look at the code because the addition of sample repeaters was quite inelegant.
@Alaete I did not put a default analytics view so you may want to consider that, but for now this will close #207 
Also, feel free to change the sample data

Add sample data

---

src/main/java/seedu/ichifund/commons/core/Messages.java
src/main/java/seedu/ichifund/logic/commands/repeater/AddRepeaterCommand.java
src/main/java/seedu/ichifund/logic/commands/repeater/DeleteRepeaterCommand.java
src/main/java/seedu/ichifund/logic/commands/repeater/EditRepeaterCommand.java
src/main/java/seedu/ichifund/model/Model.java
src/main/java/seedu/ichifund/model/ModelManager.java
src/test/java/seedu/ichifund/logic/commands/AddCommandTest.java
src/test/java/seedu/ichifund/logic/commands/budget/AddBudgetCommandTest.java
src/test/java/seedu/ichifund/testutil/ModelStub.java

Branch repeater logic
